### ISSUE TITLE
Could not locate Gemfile or .bundle/ directory

### ISSUE THREAD

**Issue by maddycpierce** [maddycpierce/ecommerce-pattern-library#2]
Hi @thomasjbradley ,

I have the files open in Atom and GitHub, and have opened Terminal and pressed the Up Arrow and then Enter (as you have instructed on your website) but Terminal keeps giving me this:

<img width="697" alt="screenshot 2019-01-23 at 2 49 05 pm" src="https://user-images.githubusercontent.com/22149579/51632767-0c753a80-1f1e-11e9-94b6-528eda7e54dd.png">

What should I do to fix this error? Thanks.

**Comment by thomasjbradley** [comment]
Looks like Terminal is not pointed to the correct folder. At the top of the Terminal window it says: "Maddy"—but it should say "ecommerce-pattern-library".

Did you press `Open in Terminal` within GitHub Desktop?

**Comment by maddycpierce** [comment]
Nope I didn't, thank you!
