### ISSUE TITLE
Pattern Library Deploy Failed

### ISSUE THREAD

**Issue by maddycpierce** [maddycpierce/ecommerce-pattern-library#3]
@thomasjbradley There wasn't enough time in class to ask you for help on this, so should I come to see you during your office hours tomorrow? Netlify keeps telling me that my pattern library deploy failed, and I also can't remember if I ended up showing you my assignments from this week. Thanks!

**Comment by thomasjbradley** [comment]
Does it work in your local Terminal? Are there any error messages?

Check the online progress tracker to see if I graded your work.

**Comment by maddycpierce** [comment]
I wasn't able to show you the assignments because of the high volume of issues everyone (including myself) was having- this must have been a very busy and tiring class for you! Is there any way that I could please still submit proof that I did complete the tasks that were due before the class and during? I have completed the "Typography and Colours" assignment, "Pattern library customization", "Making patterns", and "Buttons". Though you did see them, I didn't specifically say that I had completed them, sorry about that.

Yes, it does work in my local terminal, and there don't appear to be any error messages. I have attached an image of how the pattern library appears when I open it through Netlify, versus when I open it through the local host link that you provided in one of the in-class activities. 
<img width="697" alt="screen shot 2019-01-28 at 6 39 17 pm" src="https://user-images.githubusercontent.com/22149579/51873900-e809cb80-232c-11e9-85d4-5cc2b008d6c6.png">
<img width="1105" alt="screen shot 2019-01-28 at 6 40 34 pm" src="https://user-images.githubusercontent.com/22149579/51873901-e809cb80-232c-11e9-952a-3e197db039b1.png">
<img width="1105" alt="screen shot 2019-01-28 at 6 40 50 pm" src="https://user-images.githubusercontent.com/22149579/51873902-e809cb80-232c-11e9-99d6-c27327a4b9b9.png">

**Comment by thomasjbradley** [comment]
Try this:

1. Go to Netlify, and go into your site
2. Click "Deploys" in the top navigation
3. In the top right there’s a button: "Trigger deploy"
4. Select: "Clear cache and deploy site"

See if that works.

![screen shot 2019-01-28 at 6 50 32 pm](https://user-images.githubusercontent.com/105192/51874147-c3faba00-232d-11e9-9701-97585fe2f08b.png)

*If we get your site deployed I can look at the live website to see what you accomplished today.*

**Comment by maddycpierce** [comment]
It worked! Thank you very much.

**Comment by maddycpierce** [comment]
One more thing that I intended to ask you this morning: though I followed the steps in the lesson to create the buttons and their folders, the css doesn't seem to be connected properly as none of it will style. Do I need to add the buttons.css into the main.css for it to work?

**Comment by thomasjbradley** [comment]
I think it’s actually your `modules.css`—go get a new version of Modulifier, and press “Select all”; the default buttons weren’t included.

**Comment by thomasjbradley** [comment]
I looked over all your work & it looks fantastic. The pattern library is looking really cohesive.
