### ISSUE TITLE
Spritebot won't save sprite sheet

### ISSUE THREAD

**Issue by maddycpierce** [maddycpierce/ecommerce-pattern-library#4]
@thomasjbradley I am trying to download my svgs as a sprite sheet, but even when I select where I want the sprite to be saved, it never appears to the location that I downloaded it to. I have tried this multiple times with no luck. What can I do to fix this issue?
<img width="812" alt="screen shot 2019-02-01 at 2 45 25 pm" src="https://user-images.githubusercontent.com/22149579/52145909-4b974000-2630-11e9-9125-6cf78f8c9f79.png">
<img width="887" alt="screen shot 2019-02-01 at 2 45 31 pm" src="https://user-images.githubusercontent.com/22149579/52145912-4c2fd680-2630-11e9-882c-6c16290d8d86.png">

**Comment by thomasjbradley** [comment]
That’s super weird. Did you download a new version of Spritebot recently?

**Comment by maddycpierce** [comment]
I'm not sure. Where do I find the newest version? Also, I have tried selecting all of the modules for modules.css, but the buttons on my pattern library still don't look like the basic buttons from modules.css is working. 
<img width="491" alt="screen shot 2019-02-01 at 2 57 47 pm" src="https://user-images.githubusercontent.com/22149579/52146500-e8a6a880-2631-11e9-8c02-e9c904645b24.png">

**Comment by thomasjbradley** [comment]
Spritebot: https://github.com/thomasjbradley/spritebot#download

**Comment by thomasjbradley** [comment]
It does seem like it should be working. Do you buttons work properly on `localhost`?

**Comment by maddycpierce** [comment]
I just downloaded the newest version of Spritebot and the issue hasn't changed.  Yes, it looks like everything is working when I look at Terminal (is that localhost?).

**Comment by maddycpierce** [comment]
https://focused-euler-ab7afc.netlify.com/pattern-library/#brand The site isn't updating when I add a new pattern either. Could you please help me fix this issue?

**Comment by thomasjbradley** [comment]
Try going into the Netlify dashboard for your website. Press "Deploys" in the navigation. Then press `Trigger deploy > Clear cache & deploy site`

![screen shot 2019-02-02 at 11 05 24 am](https://user-images.githubusercontent.com/105192/52166393-9f5e6380-26da-11e9-842c-01a0591a74a9.png)

**Comment by thomasjbradley** [comment]
Can you zip the SVGs up and send them to me?

**Comment by maddycpierce** [comment]
Sure! Here are the SVGs. I cleared the cache and deployed the site, but it failed again once I committed a new change. 
[svg.zip](https://github.com/maddycpierce/ecommerce-pattern-library/files/2824594/svg.zip)
<img width="1337" alt="screen shot 2019-02-02 at 11 14 56 am" src="https://user-images.githubusercontent.com/22149579/52166497-0f211e00-26dc-11e9-9bd4-66491d05a074.png">

**Comment by thomasjbradley** [comment]
I dunno about Spritebot. We’ll have to look at it because they’re working for me.
[icons.svg.zip](https://github.com/maddycpierce/ecommerce-pattern-library/files/2824656/icons.svg.zip)

**Comment by maddycpierce** [comment]
Okay, thank you so much for all of your help, I really appreciate it.

**Comment by maddycpierce** [comment]
I thought it was working, but the site keeps failing. It publishes once if I clear cache and deploy the site, but every following time it fails.

**Comment by thomasjbradley** [comment]
Click into one of the failed deploys and send me a screenshot of the log messages.

**Comment by maddycpierce** [comment]
![screen shot 2019-02-02 at 2 35 44 pm](https://user-images.githubusercontent.com/22149579/52168387-dd1db500-26f7-11e9-8237-439553939b20.png)
