### ISSUE TITLE
Can't view Local Host

### ISSUE THREAD

**Issue by maddycpierce** [maddycpierce/ecommerce-pattern-library#5]
Hi @thomasjbradley , I haven't worked on my pattern library since Monday, so this is the first time I am encountering this issue. I am not able to view the localhost when I type http://localhost:4000 into the search bar, all that shows up is the screenshot below. Same with when I open the Netlify link. Additionally, it's still saying that the production deploy has failed. Do you have any suggestions on how I can go about fixing these issues?

![screen shot 2019-02-09 at 9 41 50 am](https://user-images.githubusercontent.com/22149579/52522125-0934bb00-2c4f-11e9-8d69-91d4ad13c65e.png)
![screen shot 2019-02-09 at 9 41 57 am](https://user-images.githubusercontent.com/22149579/52522126-0934bb00-2c4f-11e9-8a42-c27a25aa346c.png)

**Comment by maddycpierce** [comment]
Here is a screenshot of Terminal, nothing looks wrong here... I've also added the deploy log.

![screen shot 2019-02-09 at 9 44 09 am](https://user-images.githubusercontent.com/22149579/52522152-5a44af00-2c4f-11e9-90b7-3376593306e9.png)
.
<img width="697" alt="screen shot 2019-02-09 at 9 43 24 am" src="https://user-images.githubusercontent.com/22149579/52522137-32554b80-2c4f-11e9-9b4f-671a6aeafe20.png">

**Comment by thomasjbradley** [comment]
The URL in the browser screenshot isn’t `localhost` it’s Netlify. Have you tried going to http://localhost:4000 ?
