### ISSUE TITLE
Quiz

### ISSUE THREAD

**Issue by maddycpierce** [maddycpierce/ecommerce-pattern-library#6]
Hi @thomasjbradley

I finished today's quiz in class on time but didn't have a chance to show you then. Here is a screenshot of the results. Have a great day!
<img width="940" alt="Screen Shot 2019-03-25 at 10 50 00 AM" src="https://user-images.githubusercontent.com/22149579/54930796-4c40aa00-4eee-11e9-8f34-9d65a0fb6e2e.png">

**Comment by thomasjbradley** [comment]
💯
